### ISSUE TITLE
rootfs-size value too great for base

### ISSUE THREAD

**Issue by PovilasID** [izer-xyz/openwrt-imagebuilder-action#1]
I am trying to build a custom image for my spare PC and it has 128 GB drive in it.
If I set `rootfs-size: 128G` I get a `bash: 128G: value too great for base (error token is "128G")`  error on build. 
I am guessing this is because github action instance only has 500 MB free space? Or have I misconfigured something?

**Comment by sinegar** [comment]
rootfs-size is in Mb so maybe try 128000

```
rootfs-size:
    description: 'Override the default rootfs partition size in MegaBytes - ROOTFS_PARTSIZE'
```

**Comment by sinegar** [comment]
Thinking about this further, the generated image will be huge. My suggestion would be to keep the image smaller just enough space for the binaries and have a separate data partition. 

Example what I did, after using a standard openwrt image, on a Raspberry Pi:
```
cfdisk /dev/mmcblk0 # repartition
mkfs.ext4 /dev/mmcblk0p3 # format
mount /dev/mmcblk0p3 /mnt
block detect | uci import fstab # enable auto mount
uci set fstab.@mount[-1].enabled='1'
uci set fstab.@global[0].check_fs='1'
uci commit fstab # save changes
```

**Comment by PovilasID** [comment]
Having a partition for this sounds like a much better option... however, I am running docker on this machine and running those images on mounted drive could get tricky with complex docker implementation ass is.

**Comment by sinegar** [comment]
Shouldn’t be an issue. Docker stores everything (images, containers, volumes, secrets, …) in one place that you can easily change after install:

```
uci set dockerd.globals.data_root='/mnt/docker/'
uci commit
```

And you are set. I’ve been running this setup for some time and did couple of successful upgrades (recommend to backup before just in case).
