### ISSUE TITLE
Which image is default?

### ISSUE THREAD

**Issue by PovilasID** [izer-xyz/openwrt-imagebuilder-action#2]
I am building x86 image ant it has a few version in the [download page](https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/): `generic-ext4-combined-efi`; `generic-ext4-combined` ; `generic-squashfs-combined-efi` etc

Which ones equivalent is built? ext4 or squashfs; efi or non efi variant? Is there a way of setting it in the profile section or anywhere else?

**Comment by sinegar** [comment]
It depends on the ImageBuilder image (https://hub.docker.com/r/openwrt/imagebuilder/tags) that is derived from the profile you set. 

I only played with the ARM images so far but can patch the default .config using config.sed file. You can find an example in this repo that excludes ext4 image for ARM (to speed up the build). 

When you build the image it should list all the generated file in the console. 

I can point you to the right places if you share a repo.
